### ISSUE TITLE
Running on Linux?

### ISSUE THREAD

**Issue by vsoch** [bbodi/rustarok#10]
Is this game supported for running on linux? If the Rustarok files can be distributed, we could make  a container to serve it. Do you have any direct (programmatic) links for download? I'd like to try / play, but I use Linux.

**Comment by bbodi** [comment]
After some [minor tweaks](https://github.com/bbodi/rustarok/commit/225df093a121ec09564799b74dffacbb41a1e29f), it works smoothly on Linux.

**Comment by vsoch** [comment]
Awesome! Are you able to package / share the data so I can build a container for it?

**Comment by bbodi** [comment]
Just download a ragnarok client ( I suggest TalonRO [direct link](https://mega.nz/#!LjJwwABL!1fBoGC_2WFDgvVBMS6HVHTHMPG81KG3ZfpNThg6_nj8)), and set the path in the config.toml to the grf files found in the installation folder of TalonRO ([guide](https://github.com/bbodi/rustarok#running-on-windows)).

**Comment by vsoch** [comment]
That link never loads for me (page stays white, connecting) - I'm on Linux (Ubuntu) if that matters? I noticed that you sent a guide for Windows. We would want a direct link to get the data for linux - could you package it and put it somewhere to download?

**Comment by bbodi** [comment]
Unfortunately no.

Try the torrent version ([direct link](https://downloads.talonro.com/TalonRO_Full.torrent)).

**Comment by vsoch** [comment]
okay I figured out how to download a torrent, but this torrent is still an exe file. To be clear, exe is a windows executable, this won't load / install on linux. Is there some tool you want me to use or another way to inspect or extract?

**Comment by bbodi** [comment]
Oh sorry, I did not realize that they provide an exe in the torrent. Somehow you have to install it (wine?) or try to find another source to get those *.grf files (they are ~2GB, so I can't just upload them for you).

I admit it sucks if you are not familiar of this ecosystem, but unfortunately at this stage of the project it's not a priority to make this part smooth and user friendly.

**Comment by vsoch** [comment]
Got them! 

```bash
Singularity wine.sif:~/.wine/drive_c/Games/TalonRO> ls
AI	     RagnarokSetup.exe	TalonPatch.conf  dinput.ini	 ijl15.dll     rdata.grf  talonexe.exe	tpalettes.grf
Init.exe     RagnarokSetup.ini	TalonPatch.exe	 gepard.dll	 libcurl.dll   savedata   talonro.dat	txmas.grf
Mp3dec.asi   Setup.exe		binkw32.dll	 gepard.grf	 lua.exe       sdata.grf  tdata.grf	unins000.dat
Mss32.dll    Setup.ini		cps.dll		 gepard.license  msvcp110.dll  skin	  thallo.grf	unins000.exe
Mssfast.m3d  System		dinput.dll	 granny2.dll	 msvcr110.dll  talo.nro   tmp.conf
Singularity wine.sif:~/.wine/drive_c/Games/TalonRO> 
```
I needed to build a Singularity container with wine, and then download and install (from the .zip) and save to WINEPREFIX (it installs under games). What I'll do is create a repo with the Singularity recipe and instructions, and then give a go at running with rustarok. I can't promise I'll get it fully working, but at least I got those files! :D It's getting late here but likely I'll make some time to work on this soon :)
